transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0

global_frame: map
robot_base_frame: base_link
resolution: 0.05

rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}
#  - {name: sonar_layer,      type: "range_sensor_layer::RangeSensorLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: middle
  explore_clear_space: false

sensor:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, raytrace_range: $(arg sensor_range), obstacle_range: $(arg sensor_range)}

#sonar_layer:
# observation_source: sonar_f
# sonar_f: {data_type: Range, clearing: true, marking: true, topic: scan, inf_is_valid: true}
# ns: ""
# topics: ["/sonar_f"]
# no_readings_timeout: 1.0
# clear_threshold: 0.2
# mark_threshold: 0.80
# clear_on_max_reading: false

inflation:
  inflation_radius: 0.15
